openapi: 3.0.0
info:
  title: OpenDaylight
  version: 1.0.0
  description: MeasurementFunctions and ImplementationFunctions at the OpenDaylight Controller

paths:
########################################################################################################################
#   Measurements and Implementations
########################################################################################################################

  # Read MountPoints
  # Create MountPoint
  /rests/data/network-topology:network-topology/topology=topology-netconf:
    get:
      operationId: getListOfMountPoints
      summary: 'Provides a list of the configured MountPoints'
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'List of configured MountPoints provided'
          content:
            application/json:
              schema:
                type: object
                properties:
                  network-topology:topology:
                    type: array
                    items:
                      type: object
                      properties:
                        node:
                          type: array
                          x-key: node-id
                          items:
                            type: object
                            properties:
                              node-id:
                                type: string
                                description: >
                                  'deviceName defined by Telefonica planing department
                                  Invariant value defined during creation of the MountPoint'
                              netconf-node-topology:available-capabilities:
                                type: object
                                description: >
                                  'Capability
                                  Netconf capabilities as they are advertised by the Netconf server in the mediator/device'
                                properties:
                                  available-capability:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        capability:
                                          type: string
                                        capability-origin:
                                          type: string
                              netconf-node-topology:unavailable-capabilities:
                                type: object
                                description: >
                                  'Capability
                                  Netconf capabilities as they are advertised by the Netconf server in the mediator/device'
                                properties:
                                  unavailable-capability:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        capability:
                                          type: string
                                        failure-reason:
                                          type: string
                              netconf-node-topology:host:
                                type: string
                                description: >
                                  'Configuration
                                  Remote IP address, which is to be used by the NetconfClient to address the MediatorProcess'
                              netconf-node-topology:port:
                                type: integer
                                description: >
                                  'Configuration
                                  Remote TCP port, which is to be used by the NetconfClient to address the MediatorProcess'
                              netconf-node-optional:notification:
                                type: object
                                properties:
                                  subscribe:
                                    type: boolean
                                    description: >
                                      'Configuration
                                      if true, the automated subscribing for notifications while mounting is activated'
                                  stream-name:
                                    type: string
                                    description: >
                                      'Configuration
                                      Name of the stream for clients of ODL to identify it while subscribing'
                              netconf-node-topology:username:
                                type: string
                                description: >
                                  'Configuration
                                  Name of the user applied for authenticating at the MediatorProcess/device while initiating the Netconf connection'
                              netconf-node-topology:password:
                                type: string
                                description: >
                                  'Configuration
                                  Password of the user applied for authenticating at the MediatorProcess/device while initiating the Netconf connection'
                              netconf-node-topology:sleep-factor:
                                type: string
                                description: >
                                  'Configuration
                                  Factor for multiplying the time to wait with every new attempt to connect with the MediatorProcess/device'
                              netconf-node-topology:max-connection-attempts:
                                type: integer
                                description: >
                                  'Configuration
                                  Maximum number of attempts to connect with the MediatorProcess/device'
                              netconf-node-topology:default-request-timeout-millis:
                                type: integer
                                description: >
                                  'Configuration
                                  Time to waiting for the MediatorProcess/device to respond to some request, values are different by vendor'
                              netconf-node-topology:tcp-only:
                                type: boolean
                                description: >
                                  'Configuration
                                  ? ; always configured to false'
                              netconf-node-topology:concurrent-rpc-limit:
                                type: integer
                                description: >
                                  'Configuration
                                  ? ; always configured to 0'
                              netconf-node-topology:schema-cache-directory:
                                type: string
                                description: >
                                  'Configuration
                                  Location inside the ODL to where the YANG schemas provided by the MediatorProcess/device during advertising its Netconf capabilities are stored; values are different per MediatorVM/device'
                              netconf-node-topology:between-attempts-timeout-millis:
                                type: integer
                                description: >
                                  'Configuration
                                  ? ; always configured to 62500'
                              netconf-node-topology:reconnect-on-changed-schema:
                                type: boolean
                                description: >
                                  'Configuration
                                  ? ; always configured to false'
                              netconf-node-topology:keepalive-delay:
                                type: integer
                                description: >
                                  'Configuration
                                  Time to wait for the ODL to send another keep alive packet to the MediatorProcess/device'
                              netconf-node-topology:connection-status:
                                type: string
                                description: >
                                  'Status
                                  Changes from connected to connecting whenever some keep alive packet has not been answered by the MediatorProcess/device
                                  Changes from connecting to unable-to-connect whenever the number unanswered keep alive packets is exceeding the max-connection-attempts'
                              netconf-node-topology:session-id:
                                type: integer
                                description: >
                                  'Configuration
                                  Whenever a new Netconf session could be established a new session-id is created'
                example:
                  network-topology:topology:
                    - node:
                        - node-id: 'CO02060'
                          netconf-node-topology:sleep-factor: '2.5'
                          netconf-node-topology:default-request-timeout-millis: 1800000
                          netconf-node-topology:port: 17833
                          netconf-node-topology:tcp-only: false
                          netconf-node-topology:concurrent-rpc-limit: 0
                          netconf-node-topology:host: '172.28.127.9'
                          netconf-node-topology:connection-status: 'connected'
                          netconf-node-topology:session-id: 82
                          netconf-node-topology:max-connection-attempts: 8
                          netconf-node-topology:username: 'admin'
                          netconf-node-topology:password: 'admin'
                          netconf-node-topology:schema-cache-directory: 'hua'
                          netconf-node-topology:between-attempts-timeout-millis: 5000
                          netconf-node-topology:reconnect-on-changed-schema: false
                          netconf-node-topology:keepalive-delay: 120
                          netconf-node-topology:available-capabilities:
                            available-capability:
                              - capability: 'urn:ietf:params:xml:ns:yang:ietf-yang-types'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:base:1.0'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:base:1.1'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:capability:candidate:1.0'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:capability:validate:1.1'
                                capability-origin: 'device-advertised'
                          netconf-node-optional:notification:
                            subscribe: true
                            stream-name: 'NETCONF'
                        - node-id: '513559991A'
                          netconf-node-topology:sleep-factor: '2.5'
                          netconf-node-topology:default-request-timeout-millis: 900000
                          netconf-node-topology:port: 8303
                          netconf-node-topology:tcp-only: false
                          netconf-node-topology:concurrent-rpc-limit: 0
                          netconf-node-topology:host: '172.28.127.7'
                          netconf-node-topology:connection-status: 'connected'
                          netconf-node-topology:session-id: 83
                          netconf-node-topology:max-connection-attempts: 8
                          netconf-node-topology:username: 'admin'
                          netconf-node-topology:password: 'admin'
                          netconf-node-topology:schema-cache-directory: 'eric'
                          netconf-node-topology:between-attempts-timeout-millis: 5000
                          netconf-node-topology:reconnect-on-changed-schema: false
                          netconf-node-topology:keepalive-delay: 120
                          netconf-node-topology:unavailable-capabilities:
                            unavailable-capability:
                              - failure-reason: 'unable-to-resolve'
                                capability: '(http://tail-f.com/ns/aaa/1.1?revision=2015-06-16)tailf-aaa'
                              - failure-reason: 'unable-to-resolve'
                                capability: >-
                                  (http://tail-f.com/yang/netconf-monitoring?revision=2016-11-24)tailf-netconf-monitoring
                              - failure-reason: 'unable-to-resolve'
                                capability: '(http://tail-f.com/ns/kicker?revision=2017-03-16)tailf-kicker'
                              - failure-reason: 'unable-to-resolve'
                                capability: '(http://tail-f.com/ns/webui?revision=2013-03-07)tailf-webui'
                          netconf-node-topology:available-capabilities:
                            available-capability:
                              - capability: 'urn:ietf:params:netconf:base:1.0'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:base:1.1'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:capability:xpath:1.0'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:capability:candidate:1.0'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:capability:validate:1.1'
                                capability-origin: 'device-advertised'
                          netconf-node-optional:notification:
                            subscribe: true
                            stream-name: 'NETCONF'
                        - node-id: '513559991B'
                          netconf-node-topology:sleep-factor: '2.5'
                          netconf-node-topology:default-request-timeout-millis: 900000
                          netconf-node-topology:port: 8304
                          netconf-node-topology:tcp-only: false
                          netconf-node-topology:concurrent-rpc-limit: 0
                          netconf-node-topology:host: '172.28.127.7'
                          netconf-node-topology:connection-status: 'connected'
                          netconf-node-topology:session-id: 133
                          netconf-node-topology:max-connection-attempts: 8
                          netconf-node-topology:username: 'admin'
                          netconf-node-topology:password: 'admin'
                          netconf-node-topology:schema-cache-directory: 'eric'
                          netconf-node-topology:between-attempts-timeout-millis: 5000
                          netconf-node-topology:reconnect-on-changed-schema: false
                          netconf-node-topology:keepalive-delay: 120
                          netconf-node-topology:unavailable-capabilities:
                            unavailable-capability:
                              - failure-reason: 'unable-to-resolve'
                                capability: '(http://tail-f.com/ns/aaa/1.1?revision=2015-06-16)tailf-aaa'
                              - failure-reason: 'unable-to-resolve'
                                capability: >-
                                  (http://tail-f.com/yang/netconf-monitoring?revision=2016-11-24)tailf-netconf-monitoring
                              - failure-reason: 'unable-to-resolve'
                                capability: '(http://tail-f.com/ns/kicker?revision=2017-03-16)tailf-kicker'
                              - failure-reason: 'unable-to-resolve'
                                capability: '(http://tail-f.com/ns/webui?revision=2013-03-07)tailf-webui'
                          netconf-node-topology:available-capabilities:
                            available-capability:
                              - capability: 'urn:ietf:params:netconf:base:1.0'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:base:1.1'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:capability:xpath:1.0'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:capability:candidate:1.0'
                                capability-origin: 'device-advertised'
                              - capability: 'urn:ietf:params:netconf:capability:validate:1.1'
                                capability-origin: 'device-advertised'
                          netconf-node-optional:notification:
                            subscribe: true
                            stream-name: 'NETCONF'
    post:
      operationId: postConstructMountPoint
      summary: 'Establishes a new MountPoint'
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - network-topology:node
              properties:
                network-topology:node:
                  type: array
                  x-key: node-id
                  items:
                    type: object
                    required:
                      - node-id
                    properties:
                      node-id:
                        type: string
                        description: >
                          'deviceName defined by Telefonica planing department
                          Invariant value defined during creation of the MountPoint
                          from [p1ConstructMountPoint$request.body#mount-name]'
              example:
                network-topology:node:
                  - node-id: '111251111'
      responses:
        '201':
          description: 'MountPoint established'

  # Delete MountPoint
  # Modify MountPoint
  /rests/data/network-topology:network-topology/topology=topology-netconf/node={mount-name}:
    delete:
      operationId: deleteDestructMountPoint
      summary: 'Deletes specified MountPoint'
      parameters:
        - in: path
          name: 'mount-name'
          required: true
          schema:
            type: string
            description: >
              'from [p1DestructMountPoint$request.body#mount-name]'
      security:
        - basicAuth: []
      responses:
        '204':
          description: 'MountPoint deleted'
    put:
      operationId: putReconstructMountPoint
      summary: 'Updates specified MountPoint'
      parameters:
        - in: path
          name: 'mount-name'
          required: true
          schema:
            type: string
            description: >
              'from [p1ReconstructMountPoint$request.body#mount-name]'
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - network-topology:node
              properties:
                network-topology:node:
                  type: array
                  items:
                    type: object
                    required:
                      - node-id
                      - netconf-node-topology:host
                      - netconf-node-topology:port
                      - netconf-node-optional:notification
                      - netconf-node-topology:username
                      - netconf-node-topology:password
                      - netconf-node-topology:sleep-factor
                      - netconf-node-topology:max-connection-attempts
                      - netconf-node-topology:default-request-timeout-millis
                      - netconf-node-topology:tcp-only
                      - netconf-node-topology:concurrent-rpc-limit
                      - netconf-node-topology:schema-cache-directory
                      - netconf-node-topology:between-attempts-timeout-millis
                      - netconf-node-topology:reconnect-on-changed-schema
                      - netconf-node-topology:keepalive-delay
                    properties:
                      node-id:
                        type: string
                        description: >
                          'deviceName defined by Telefonica planing department
                          Invariant value defined during creation of the MountPoint'
                      netconf-node-topology:host:
                        type: string
                        description: >
                          'Configuration
                          Remote IP address, which is to be used by the NetconfClient to address the MediatorProcess
                          from [p1ReconstructMountPoint$request.body#remote-ip-address]'
                      netconf-node-topology:port:
                        type: integer
                        description: >
                          'Configuration
                          Remote TCP port, which is to be used by the NetconfClient to address the MediatorProcess
                          from [p1ReconstructMountPoint$request.body#remote-port]'
                      netconf-node-optional:notification:
                        type: object
                        required:
                          - subscribe
                          - stream-name
                        properties:
                          subscribe:
                            type: boolean
                            description: >
                              'Configuration
                              if true, the automated subscribing for notifications while mounting is activated
                              from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/notification-subscribe]'
                          stream-name:
                            type: string
                            description: >
                              'Configuration
                              Name of the stream for clients of ODL to identify it while subscribing
                              from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/notification-stream-name]'
                      netconf-node-topology:username:
                        type: string
                        description: >
                          'Configuration
                          Name of the user applied for authenticating at the MediatorProcess/device while initiating the Netconf connection
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/netconf-user-name]'
                      netconf-node-topology:password:
                        type: string
                        description: >
                          'Configuration
                          Password of the user applied for authenticating at the MediatorProcess/device while initiating the Netconf connection
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/netconf-password]'
                      netconf-node-topology:sleep-factor:
                        type: string
                        description: >
                          'Configuration
                          Factor for multiplying the time to wait with every new attempt to connect with the MediatorProcess/device
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/sleep-factor]'
                      netconf-node-topology:max-connection-attempts:
                        type: integer
                        description: >
                          'Configuration
                          Maximum number of attempts to connect with the MediatorProcess/device
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/max-connection-attempts]'
                      netconf-node-topology:default-request-timeout-millis:
                        type: integer
                        description: >
                          'Configuration
                          Time to waiting for the MediatorProcess/device to respond to some request, values are different by vendor
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/default-request-timeout-millis]'
                      netconf-node-topology:tcp-only:
                        type: boolean
                        description: >
                          'Configuration
                          ?
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/tcp-only]'
                      netconf-node-topology:concurrent-rpc-limit:
                        type: integer
                        description: >
                          'Configuration
                          ?
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/concurrent-rpc-limit]'
                      netconf-node-topology:schema-cache-directory:
                        type: string
                        description: >
                          'Configuration
                          Location inside the ODL to where the YANG schemas provided by the MediatorProcess/device during advertising its Netconf capabilities are stored; values are different per MediatorVM/device
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/schema-cache-directory]'
                      netconf-node-topology:between-attempts-timeout-millis:
                        type: integer
                        description: >
                          'Configuration
                          ?
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/between-attempts-timeout-millis]'
                      netconf-node-topology:reconnect-on-changed-schema:
                        type: boolean
                        description: >
                          'Configuration
                          ?
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/reconnect-on-changed-schema]'
                      netconf-node-topology:keepalive-delay:
                        type: integer
                        description: >
                          'Configuration
                          Time to wait for the ODL to send another keep alive packet to the MediatorProcess/device
                          from [/network-control-domain=running/profile=[p1ReconstructMountPoint$request.body#mount-point-template-name]/keepalive-delay]'
              example:
                network-topology:node:
                  - node-id: '111251111'
                    netconf-node-topology:host: '172.28.127.7'
                    netconf-node-topology:port: 8301
                    netconf-node-optional:notification:
                      subscribe: true
                      stream-name: 'NETCONF'
                    netconf-node-topology:username: 'admin'
                    netconf-node-topology:password: 'admin'
                    netconf-node-topology:sleep-factor: '2.5'
                    netconf-node-topology:max-connection-attempts: 8
                    netconf-node-topology:default-request-timeout-millis: 900000
                    netconf-node-topology:tcp-only: false
                    netconf-node-topology:concurrent-rpc-limit: 0
                    netconf-node-topology:schema-cache-directory: 'eric'
                    netconf-node-topology:between-attempts-timeout-millis: 5000
                    netconf-node-topology:reconnect-on-changed-schema: false
                    netconf-node-topology:keepalive-delay: 120
      responses:
        '204':
          description: 'MountPoint updated'

  # Read User Definitions
  # Create User Definition
  /auth/v1/users:
    get:
      operationId: getListOfUsers
      summary: 'Provides a list of the configured users'
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'List of configured users provided'
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        userid:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        enabled:
                          type: integer
                        email:
                          type: string
                          format: email
                        password:
                          type: string
                        salt:
                          type: string
                        domainid:
                          type: string
                example:
                  users:
                    - userid: 'mwdi@sdn'
                      name: 'mwdi'
                      description: ''
                      enabled: 1
                      email: ''
                      password: '**********'
                      salt: '**********'
                      domainid: 'sdn'
                    - userid: 'mwdg@sdn'
                      name: 'mwdg'
                      description: ''
                      enabled: 1
                      email: ''
                      password: '**********'
                      salt: '**********'
                      domainid: 'sdn'
                    - userid: 'matr@sdn'
                      name: 'matr'
                      description: ''
                      enabled: 1
                      email: ''
                      password: '**********'
                      salt: '**********'
                      domainid: 'sdn'
    post:
      operationId: postConstructUser
      summary: 'Establishes a new user'
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - password
                - domainid
              properties:
                name:
                  type: string
                password:
                  type: string
                domainid:
                  type: string
              example:
                name: 'user.name'
                password: 'geheim'
                domainid: 'sdn'
      responses:
        '201':
          description: 'User established'
          content:
            application/json:
              schema:
                type: object
                properties:
                  userid:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  enabled:
                    type: integer
                  email:
                    type: string
                    format: email
                  password:
                    type: string
                  salt:
                    type: string
                  domainid:
                    type: string
                example:
                  userid: 'user.name@sdn'
                  name: 'user.name'
                  description: ''
                  enabled: 1
                  email: ''
                  password: '**********'
                  salt: '**********'
                  domainid: 'sdn'

  # Read Role Definitions
  # Create Role Definition
  /auth/v1/roles:
    get:
      operationId: getListOfRoles
      summary: 'Provides a list of the configured roles'
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'List of configured roles provided'
          content:
            application/json:
              schema:
                type: object
                properties:
                  roles:
                    type: array
                    items:
                      type: object
                      properties:
                        roleid:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        domainid:
                          type: string
                example:
                  roles:
                    - roleid: 'user@sdn'
                      name: 'user'
                      description: ''
                      domainid: 'sdn'
                    - roleid: 'monitor@sdn'
                      name: 'monitor'
                      description: ''
                      domainid: 'sdn'
                    - roleid: 'planner@sdn'
                      name: 'planner'
                      description: ''
                      domainid: 'sdn'
                    - roleid: 'siae@sdn'
                      name: 'siae'
                      description: ''
                      domainid: 'sdn'
    post:
      operationId: postConstructRole
      summary: 'Establishes a new role'
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - domainid
              properties:
                name:
                  type: string
                domainid:
                  type: string
              example:
                name: 'role.name'
                domainid: 'sdn'
      responses:
        '201':
          description: 'Role established'
          content:
            application/json:
              schema:
                type: object
                properties:
                  roleid:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  domainid:
                    type: string
                example:
                  roleid: 'role.name@sdn'
                  name: 'role.name'
                  description: ''
                  domainid: 'sdn'

  # Read Roles/Groups a User is associated with
  # Create User Role association (Grant)
  /auth/v1/domains/sdn/users/{userid}/roles:
    parameters:
      - in: path
        name: userid
        schema:
          type: string
        required: true
        description: 'user for which associated roles shall be provided'
    get:
      operationId: getListOfRolesOfaUser
      summary: 'Provides the list of roles that are associated with a user'
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'List of roles provided'
          content:
            application/json:
              schema:
                type: object
                properties:
                  roles:
                    type: array
                    items:
                      type: object
                      properties:
                        roleid:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        domainid:
                          type: string
                example:
                  roles:
                    - roleid: 'power-user@sdn'
                      name: 'power-user'
                      description: ''
                      domainid: 'sdn'
                    - roleid: 'planner@sdn'
                      name: 'planner'
                      description: ''
                      domainid: 'sdn'
    post:
      operationId: postConstructRoleAssociation
      summary: 'Establishes a new role association'
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - roleid
                - domainid
              properties:
                roleid:
                  type: string
                domainid:
                  type: string
              example:
                roleid: 'siae@sdn'
                domainid: 'sdn'
      responses:
        '201':
          description: 'Role association established'
          content:
            application/json:
              schema:
                type: object
                properties:
                  grantid:
                    type: string
                  domainid:
                    type: string
                  userid:
                    type: string
                  roleid:
                    type: string
                example:
                  grantid: 'user.name@sdn@siae@sdn@sdn'
                  domainid: 'sdn'
                  userid: 'user.name'
                  roleid: 'siae@sdn'

  # Read Resources with associated Role/Group Permissions
  /rests/data/aaa:http-authorization:
    get:
      operationId: getListOfResourcesWithRolePermissions
      summary: 'Provides a list of resources with associated role permissions'
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'List of resources with permissions provided'
          content:
            application/json:
              schema:
                type: object
                properties:
                  aaa:http-authorization:
                    type: object
                    properties:
                      policies:
                        type: object
                        properties:
                          policies:
                            type: array
                            items:
                              type: object
                              properties:
                                resource:
                                  type: string
                                  example: '/restconf/**'
                                permissions:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      role:
                                        type: string
                                        example: 'admin'
                                      actions:
                                        type: array
                                        items:
                                          type: string
                                          example: 'get'
                                index:
                                  type: integer
                                  example: 0
                example:
                  aaa:http-authorization:
                    policies:
                      policies:
                        - resource: '/rests/data/network-topology:network-topology/topology=topology-netconf/node=513250006/**'
                          permissions:
                            - role: 'power-user@sdn'
                              actions:
                                - 'post'
                                - 'get'
                                - 'patch'
                                - 'put'
                                - 'delete'
                            - role: 'siae'
                              actions:
                                - 'get'

                          index: 0
                        - resource: '/rests/data/network-topology:network-topology/topology=topology-netconf/**'
                          permissions:
                            - role: 'power-user@sdn'
                              actions:
                                - 'post'
                                - 'get'
                                - 'patch'
                                - 'put'
                                - 'delete'
                          index: 1

  # Read Permissions on ManagementDomain
  # Modify Permissions on ManagementDomain
  /rests/data/aaa:http-authorization/policies/policies=%2Frests%2Fdata%2Fnetwork-topology:network-topology%2Ftopology%3Dtopology-netconf%2F**:
    get:
      operationId: getPermissionsOnManagementDomain
      summary: 'Provides the list permissions on the ManagementDomain'
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'List of permissions provided'
          content:
            application/json:
              schema:
                type: object
                properties:
                  aaa:policies:
                    type: array
                    items:
                      type: object
                      properties:
                        resource:
                          type: string
                        permissions:
                          type: array
                          items:
                            type: object
                            properties:
                              role:
                                type: string
                              actions:
                                type: array
                                items:
                                  type: string
                                  enum:
                                  - 'post'
                                  - 'get'
                                  - 'patch'
                                  - 'put'
                                  - 'delete'
                        index:
                          type: integer
                example:
                  aaa:policies:
                    - resource: '/rests/data/network-topology:network-topology/topology=topology-netconf/**'
                      permissions:
                        - role: 'admin'
                          actions:
                            - 'post'
                            - 'get'
                            - 'patch'
                            - 'put'
                            - 'delete'
                        - role: 'provisioner'
                          actions:
                            - 'post'
                            - 'get'
                            - 'patch'
                            - 'put'
                            - 'delete'
                        - role: 'planner'
                          actions:
                            - 'get'
                        - role: 'monitor'
                          actions:
                            - 'get'
                      index: 16
    put:
      operationId: putPermission
      summary: 'Establishes a new permission on the ManagementDomain'
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - aaa:policies
              properties:
                aaa:policies:
                  type: array
                  items:
                    type: object
                    required:
                      - resource
                      - permissions
                      - index
                    properties:
                      resource:
                        type: string
                      permissions:
                        type: array
                        items:
                          type: object
                          required:
                            - role
                            - actions
                          properties:
                            role:
                              type: string
                            actions:
                              type: array
                              items:
                                type: string
                                enum:
                                - 'post'
                                - 'get'
                                - 'patch'
                                - 'put'
                                - 'delete'
                      index:
                        type: integer
              example:
                aaa:policies:
                  - resource: '/rests/data/network-topology:network-topology/topology=topology-netconf/**'
                    permissions:
                      - role: 'admin'
                        actions:
                          - 'post'
                          - 'get'
                          - 'patch'
                          - 'put'
                          - 'delete'
                      - role: 'provisioner'
                        actions:
                          - 'post'
                          - 'get'
                          - 'patch'
                          - 'put'
                          - 'delete'
                      - role: 'planner'
                        actions:
                          - 'get'
                      - role: 'monitor'
                        actions:
                          - 'get'
                    index: 16
      responses:
        '204':
          description: 'Permissions established'


########################################################################################################################
#   Common Components
########################################################################################################################
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
