openapi: 3.0.0
info:
  title: ControllerDomainManager
  version: 1.0.0

paths:
########################################################################################################################
#   Service Layer - Individual Part
########################################################################################################################

  /p1/construct-management-domain-interface-at-odl:
    post:
      operationId: p1ConstructManagementDomainInterfaceAtOdl
      summary: 'Creates an additional ManagementDomainInterface at a Controller'
      tags:
        - PrivateServices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - controller-name
                - http-user-name
                - http-password
                - http-methods
              properties:
                controller-name:
                  type: string
                  description: >
                    'controllerName

                    remoteIpAddress = [/network-control-domain=running/control-construct=[controllerName]/logical-termination-point=controller-manager/layer-protocol=tcp-server/local-ip-address]
                    remotePort = [/network-control-domain=running/control-construct=[controllerName]/logical-termination-point=controller-manager/layer-protocol=tcp-server/local-port]
                    adminUser = [/network-control-domain=running/control-construct=[controllerName]/logical-termination-point=controller-manager/layer-protocol=http-server/http-user-name]
                    adminPassword = [/network-control-domain=running/control-construct=[controllerName]/logical-termination-point=controller-manager/layer-protocol=http-server/http-password]

                    execute callback:CreateUser
                    execute callback:CreateRole
                    execute callback:AssociateUserWithRole
                    execute callback:ReadRolesAtManagementDomain
                    extend list of roles by new role and actions
                    execute callback:WriteRolesAtManagementDomain
                    '
                http-user-name:
                  type: string
                  description: 'applicationName'
                http-password:
                  type: string
                  description: 'httpPassword'
                http-methods:
                  type: array
                  description: 'httpMethods'
                  items:
                    type: string
                    enum:
                    - 'post'
                    - 'get'
                    - 'patch'
                    - 'put'
                    - 'delete'
              example:
                controller-name: 'odl-1-production'
                http-user-name: 'mwdi-201-production'
                http-password: 'geheim'
                http-methods:
                  - 'get'
      responses:
        '204':
          description: 'Additional ManagementDomainInterface created'
      callbacks:
        CreateUser:
          url: #[remoteIpAddress]:[remotePort][/auth/v1/users]
            post:
              security:
                - basicAuth: []
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      required:
                        - name
                        - password
                        - domainid
                      properties:
                        name:
                          type: string
                          description: >
                            'applicationName
                            from [request.body#http-user-name]'
                        password:
                          type: string
                          description: >
                            'httpPassword
                            from [request.body#http-password]'
                        domainid:
                          type: string
                          enum:
                            - 'sdn'
                      example:
                        name: 'mwdi-201-production'
                        password: 'geheim'
                        domainid: 'sdn'
              responses:
                '201':
                  description: 'User established'
                  content:
                    application/json:
                      schema:
                        type: object
        CreateRole:
          url: #[remoteIpAddress]:[remotePort][/auth/v1/roles]
            post:
              security:
                - basicAuth: []
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      required:
                        - name
                        - domainid
                      properties:
                        name:
                          type: string
                          description: >
                            'roleName = chosen to equal applicationName
                            from [request.body#http-user-name]'
                        domainid:
                          type: string
                          enum:
                            - 'sdn'
                      example:
                        name: 'mwdi-201-production'
                        domainid: 'sdn'
              responses:
                '201':
                  description: 'Role established'
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          roleid:
                            type: string
                            description: 'roleId'
                        example:
                          roleid: 'mwdi-201-production@sdn'
        AssociateUserWithRole:
          url: #[remoteIpAddress]:[remotePort][/auth/v1/domains/sdn/users/{userid}/roles]
            parameters:
              - in: path
                name: userid
                schema:
                  type: string
                required: true
                description: >
                  'applicationName
                  from [request.body#http-user-name]'
            post:
              security:
                - basicAuth: []
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      required:
                        - roleid
                        - domainid
                      properties:
                        roleid:
                          type: string
                          description: >
                            'roleId
                            from [callback:CreateRole$response.body#roleid]'
                        domainid:
                          type: string
                          enum:
                            - 'sdn'
                      example:
                        roleid: 'mwdi-201-production@sdn'
                        domainid: 'sdn'
              responses:
                '201':
                  description: 'Role association established'
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          grantid:
                            type: string
                          domainid:
                            type: string
                          userid:
                            type: string
                          roleid:
                            type: string
                        example:
                          grantid: 'mwdi-201-production@sdn@mwdi-201-production@sdn@sdn'
                          domainid: 'sdn'
                          userid: 'mwdi-201-production'
                          roleid: 'siae@sdn'
        ReadRolesAtManagementDomain:
          url: #[remoteIpAddress]:[remotePort][/rests/data/aaa:http-authorization/policies/policies=%2Frests%2Fdata%2Fnetwork-topology:network-topology%2Ftopology%3Dtopology-netconf%2F**]
            get:
              security:
                - basicAuth: []
              responses:
                '200':
                  description: 'List of permissions provided'
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          aaa:policies:
                            type: array
                            items:
                              type: object
                              properties:
                                resource:
                                  type: string
                                permissions:
                                  type: array
                                  description: 'permissions[*]'
                                  items:
                                    type: object
                                    properties:
                                      role:
                                        type: string
                                      actions:
                                        type: array
                                        items:
                                          type: string
                                          enum:
                                          - 'post'
                                          - 'get'
                                          - 'patch'
                                          - 'put'
                                          - 'delete'
                                index:
                                  type: integer
                                  description: 'index'
                        example:
                          aaa:policies:
                            - resource: '/rests/data/network-topology:network-topology/topology=topology-netconf/**'
                              permissions:
                                - role: 'mwdi-120-production'
                                  actions:
                                    - 'get'
                              index: 16
        WriteRolesAtManagementDomain:
          url: #[remoteIpAddress]:[remotePort][/rests/data/aaa:http-authorization/policies/policies=%2Frests%2Fdata%2Fnetwork-topology:network-topology%2Ftopology%3Dtopology-netconf%2F**]
            put:
              security:
                - basicAuth: []
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      required:
                        - aaa:policies
                      properties:
                        aaa:policies:
                          type: array
                          items:
                            type: object
                            required:
                              - resource
                              - permissions
                              - index
                            properties:
                              resource:
                                type: string
                                enum:
                                  - '/rests/data/network-topology:network-topology/topology=topology-netconf/**'
                              permissions:
                                type: array
                                description: >
                                  'permissions[*]
                                  from [ callback:ReadRolesAtManagementDomain$response.body#permissions
                                           but complemented with additional combination of role and actions as described below 
                                           if role would already exist, associated actions to be overwritten with new values ]'
                                items:
                                  type: object
                                  required:
                                    - role
                                    - actions
                                  properties:
                                    role:
                                      type: string
                                      description: >
                                        'applicationName
                                        found or created from [request.body#http-user-name]'
                                    actions:
                                      type: array
                                      description: >
                                        'httpMethods
                                        from [request.body#http-methods[*]]'
                                      items:
                                        type: string
                              index:
                                type: integer
                                description: >
                                  'index
                                  from [callback:ReadRolesAtManagementDomain$response.body#index]'
                      example:
                        aaa:policies:
                          - resource: '/rests/data/network-topology:network-topology/topology=topology-netconf/**'
                            permissions:
                              - role: 'mwdi-120-production'
                                actions:
                                  - 'get'
                              - role: 'mwdi-201-production'
                                actions:
                                  - 'get'
                            index: 16
              responses:
                '204':
                  description: 'Permissions established'


########################################################################################################################
#   Common Components
########################################################################################################################
components:
  parameters:
    user:
      name: user
      in: header
      required: true
      schema:
        type: string
        example: 'User Name'
      description: 'User identifier from the system starting the service call'
    originator:
      name: originator
      in: header
      required: true
      schema:
        type: string
        minLength: 3
        example: 'Resolver'
      description: >
        'Identification for the system consuming the API, as defined in
         [/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]'
    x-correlator:
      name: x-correlator
      in: header
      required: true
      schema:
        type: string
        pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses'
    trace-indicator:
      name: trace-indicator
      in: header
      required: true
      schema:
        type: string
        pattern: '^([0-9]+)(\.([0-9]+))*$'
        example: '1.3.1'
      description: 'Sequence of request numbers along the flow'
    customer-journey:
      name: customer-journey
      in: header
      required: true
      schema:
        type: string
        example: 'Unknown value'
      description: 'Holds information supporting customer’s journey to which the execution applies'
  responses:
    responseForErroredServiceRequests:
      description: 'Response in case of errored service requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
      headers:
        x-correlator:
          schema:
            type: string
            pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
            example: '550e8400-e29b-11d4-a716-446655440000'
          description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
        exec-time:
          schema:
            type: integer
            example: 1100
          description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
    responseForErroredOamRequests:
      description: 'Response in case of errored OaM requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
    '429':
      description: 'Response in case too many requests need to be executed in parallel or too many requests have been received within a time period. The maximum number of parallel requests is defined in an IntegerProfile with the service name as a prefix and MaxNumberOfParallelRequests as a suffix. Some time period to elapse for throttling incoming requests is defined in an IntegerProfile with the service name as a prefix and ThrottlingPeriod as a suffix'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 429
                maximum: 429
                format: int32
              message:
                type: string
                enum:
                  - 'Too many requests'
    '460':
      description: 'Response in case the mountName provided in the request is not found in the list of connected devices'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 460
                maximum: 460
                format: int32
              message:
                type: string
                enum:
                  - 'Not connected. Requested device is currently not in connected state at the controller'
    '461':
      description: 'Response in case the (parent) topology object provided in the request (body or path) is not found in the cache.'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 461
                maximum: 461
                format: int32
              message:
                type: string
                enum:
                  - 'Not available. The topology (parent) object is currently not found in the cache.'
    '470':
      description: 'Response in case the resource specified in the request does not exist within the connected device'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 470
                maximum: 470
                format: int32
              message:
                type: string
                enum:
                  - 'Resource not existing. Device informs about addressed resource unknown'
    '471':
      description: 'Response in case the (child) topology object specified in the request (body or path) does not exist within the cache.'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 471
                maximum: 471
                format: int32
              message:
                type: string
                enum:
                  - '(Child) topology object not existing. Cache informs about addressed resource unknown.'
    '502':
      description: 'Response in case the server is acting as a gateway or proxy and received an invalid response from the upstream server (device or application providing a consumed service)'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 502
                maximum: 502
                format: int32
              message:
                type: string
                enum:
                  - 'Bad Gateway'
    '530':
      description: 'Response in case the referenced resource exists (e.g. device connected and resource exists in internal data tree), but response data is either not available, lost during transmission, incomplete or corrupted'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 530
                maximum: 530
                format: int32
              message:
                type: string
                enum:
                  - 'Data invalid. Response data not available, incomplete or corrupted'
    '531':
      description: 'Response in case the server is acting as a gateway or proxy and was unable to authenticate at the upstream server (device or application providing a consumed service)'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 531
                maximum: 531
                format: int32
              message:
                type: string
                enum:
                  - 'Bad Gateway. Authentication at upstream server failed.'
    '532':
      description: 'Response in case the server is acting as a gateway or proxy and was unable to connect to the upstream server (device or application providing a consumed service)'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 532
                maximum: 532
                format: int32
              message:
                type: string
                enum:
                  - 'Bad Gateway. Upstream server not responding.'
    '533':
      description: 'Response in case the referenced resource for an connected device does not exist at the controller.'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 533
                maximum: 533
                format: int32
              message:
                type: string
                enum:
                  - 'Resource unknown. The resource for the connected device does not exist at the Controller'
    '550':
      description: 'Response in case that the application wants to call a service specified by the requestor (e.g., to return data after a long taking  data retrieval) during a service call to the application and the service information cannot be found.'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 550
                maximum: 550
                format: int32
              message:
                type: string
                enum:
                  - 'Requestor information for callback execution not found.'
  schemas:
    errorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    genericRepresentation:
      type: object
      required:
        - response-value-list
        - consequent-action-list
      properties:
        response-value-list:
          type: array
          items:
            type: object
            required:
              - field-name
              - value
              - datatype
            properties:
              field-name:
                type: string
                description: >
                  'Field name
                  from [/core-model-1-4:control-construct/profile-collection/profile=cdm-1-0-0-response-p-*/response-profile-1-0:response-profile-pac/response-profile-capability/field-name]'
              value:
                type: string
                description: >
                  'Field value
                  from [/core-model-1-4:control-construct/profile-collection/profile=cdm-1-0-0-response-p-*/response-profile-1-0:response-profile-pac/response-profile-configuration/value]'
              datatype:
                type: string
                description: >
                  'Field datatype
                  from [/core-model-1-4:control-construct/profile-collection/profile=cdm-1-0-0-response-p-*/response-profile-1-0:response-profile-pac/response-profile-capability/datatype]'
        consequent-action-list:
          type: array
          items:
            type: object
            required:
              - label
              - request
              - display-in-new-browser-window
            properties:
              label:
                type: string
                description: >
                  'Label that shall be presented on the button
                  from [/core-model-1-4:control-construct/profile-collection/profile=cdm-1-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/label]'
              request:
                type: string
                description: >
                  'Request that shall be called, when button gets pressed
                  from
                  [{/core-model-1-4:control-construct/logical-termination-point=cdm-1-0-0-tcp-s-000/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-protocol}]
                  ://
                  [{/core-model-1-4:control-construct/logical-termination-point=cdm-1-0-0-tcp-s-000/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-address/ipv-4-address}
                  or
                  {/core-model-1-4:control-construct/logical-termination-point=cdm-1-0-0-tcp-s-000/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-address/domain-name}]
                  :
                  [{/core-model-1-4:control-construct/logical-termination-point=cdm-1-0-0-tcp-s-000/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-port}]
                  [{/core-model-1-4:control-construct/profile-collection/profile=cdm-1-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-configuration/consequent-operation-reference}]'
              input-value-list:
                type: array
                items:
                  type: object
                  required:
                    - field-name
                  properties:
                    field-name:
                      type: string
                      description: >
                        'Name of an input value required for executing the Request
                        from [/core-model-1-4:control-construct/profile-collection/profile=cdm-1-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-list=*/name]'
                    unit:
                      type: string
                      description: >
                        'Unit of an input value required for executing the Request
                        from [/core-model-1-4:control-construct/profile-collection/profile=cdm-1-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-list=*/unit]'
              display-in-new-browser-window:
                type: boolean
                description: >
                  'True in case Request shall be represented in a new browser window
                  from [/core-model-1-4:control-construct/profile-collection/profile=cdm-1-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/display-in-new-browser-window]'
    logicalTerminationPoint:
      type: object
      required:
        - uuid
        - ltp-direction
        - client-ltp
        - server-ltp
        - layer-protocol
      properties:
        uuid:
          type: string
        ltp-direction:
          type: string
        client-ltp:
          type: array
          uniqueItems: true
          items:
            type: string
        server-ltp:
          type: array
          uniqueItems: true
          items:
            type: string
        layer-protocol:
          type: array
          minItems: 1
          maxItems: 1
          items:
            oneOf:
              - description: 'operation server'
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - operation-server-interface-1-0:operation-server-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  operation-server-interface-1-0:operation-server-interface-pac:
                    type: object
                    required:
                      - operation-server-interface-capability
                      - operation-server-interface-configuration
                    properties:
                      operation-server-interface-capability:
                        type: object
                        required:
                          - operation-name
                        properties:
                          operation-name:
                            type: string
                      operation-server-interface-configuration:
                        type: object
                        required:
                          - life-cycle-state
                        properties:
                          life-cycle-state:
                            type: string
              - description: 'http server'
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - http-server-interface-1-0:http-server-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  http-server-interface-1-0:http-server-interface-pac:
                    type: object
                    required:
                      - http-server-interface-capability
                    properties:
                      http-server-interface-capability:
                        type: object
                        required:
                          - application-name
                          - release-number
                          - data-update-period
                        properties:
                          application-name:
                            type: string
                          release-number:
                            type: string
                          data-update-period:
                            type: string
              - description: 'tcp server'
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - tcp-server-interface-1-0:tcp-server-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  tcp-server-interface-1-0:tcp-server-interface-pac:
                    type: object
                    required:
                      - tcp-server-interface-configuration
                    properties:
                      tcp-server-interface-configuration:
                        type: object
                        required:
                          - description
                          - local-protocol
                          - local-address
                          - local-port
                        properties:
                          description:
                            type: string
                          local-protocol:
                            type: string
                          local-address:
                            type: object
                            properties:
                              ipv-4-address:
                                type: string
                              domain-name:
                                type: string
                          local-port:
                            type: integer
              - description: 'operation client'
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - operation-client-interface-1-0:operation-client-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  operation-client-interface-1-0:operation-client-interface-pac:
                    type: object
                    required:
                      - operation-client-interface-configuration
                      - operation-client-interface-status
                    properties:
                      operation-client-interface-configuration:
                        type: object
                        required:
                          - operation-name
                        properties:
                          operation-name:
                            type: string
                      operation-client-interface-status:
                        type: object
                        required:
                          - operational-state
                          - life-cycle-state
                        properties:
                          operational-state:
                            type: string
                          life-cycle-state:
                            type: string
              - description: 'elasticsearch client'
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - elasticsearch-client-interface-1-0:elasticsearch-client-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  elasticsearch-client-interface-1-0:elasticsearch-client-interface-pac:
                    type: object
                    required:
                      - elasticsearch-client-interface-configuration
                      - elasticsearch-client-interface-status
                    properties:
                      elasticsearch-client-interface-configuration:
                        type: object
                        required:
                          - index-alias
                        properties:
                          index-alias:
                            type: string
                      elasticsearch-client-interface-status:
                        type: object
                        required:
                          - operational-state
                          - life-cycle-state
                        properties:
                          operational-state:
                            type: string
                          life-cycle-state:
                            type: string
              - description: 'mongodb client'
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - mongodb-client-interface-1-0:mongodb-client-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  mongodb-client-interface-1-0:mongodb-client-interface-pac:
                    type: object
                    required:
                      - mongodb-client-interface-configuration
                      - mongodb-client-interface-status
                    properties:
                      mongodb-client-interface-configuration:
                        type: object
                        required:
                          - database-name
                          - collection-name
                        properties:
                          database-name:
                            type: string
                          collection-name:
                            type: string
                      mongodb-client-interface-status:
                        type: object
                        required:
                          - operational-state
                          - life-cycle-state
                        properties:
                          operational-state:
                            type: string
                          life-cycle-state:
                            type: string
              - description: 'kafka client'
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - kafka-client-interface-1-0:kafka-client-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  kafka-client-interface-1-0:kafka-client-interface-pac:
                    type: object
                    required:
                      - kafka-client-interface-configuration
                      - kafka-client-interface-status
                    properties:
                      kafka-client-interface-configuration:
                        type: object
                        required:
                          - topic-name
                        properties:
                          topic-name:
                            type: string
                      kafka-client-interface-status:
                        type: object
                        required:
                          - operational-state
                          - life-cycle-state
                        properties:
                          operational-state:
                            type: string
                          life-cycle-state:
                            type: string
              - description: 'http client'
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - http-client-interface-1-0:http-client-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  http-client-interface-1-0:http-client-interface-pac:
                    type: object
                    required:
                      - http-client-interface-configuration
                    properties:
                      http-client-interface-configuration:
                        type: object
                        required:
                          - application-name
                          - release-number
                        properties:
                          application-name:
                            type: string
                          release-number:
                            type: string
              - description: 'tcp client'
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - tcp-client-interface-1-0:tcp-client-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  tcp-client-interface-1-0:tcp-client-interface-pac:
                    type: object
                    required:
                      - tcp-client-interface-configuration
                    properties:
                      tcp-client-interface-configuration:
                        type: object
                        required:
                          - remote-protocol
                          - remote-address
                          - remote-port
                        properties:
                          remote-protocol:
                            type: string
                          remote-address:
                            type: object
                            properties:
                              ip-address:
                                type: object
                                properties:
                                  ipv-4-address:
                                    type: string
                              domain-name:
                                type: string
                          remote-port:
                            type: integer
    forwardingDomain:
      type: object
      required:
        - uuid
        - forwarding-construct
      properties:
        uuid:
          type: string
        forwarding-construct:
          type: array
          items:
            type: object
            required:
              - uuid
              - name
              - fc-port
            properties:
              uuid:
                type: string
              name:
                type: array
                items:
                  type: object
                  required:
                    - value-name
                    - value
                  properties:
                    value-name:
                      type: string
                    value:
                      type: string
              fc-port:
                type: array
                items:
                  type: object
                  required:
                    - local-id
                    - port-direction
                    - logical-termination-point
                  properties:
                    local-id:
                      type: string
                    port-direction:
                      type: string
                    logical-termination-point:
                      type: string
    errorObject:
      type: object
      required:
        - _error-code
        - date-of-creation
        - past-attempts-to-fix
        - date-of-next-attempt-to-fix
      properties:
        _error-code:
          type: integer
          description: 'Reference towards a definition of an error-code (value must be unique and invariant)'
        date-of-creation:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})$'
          description: 'Date and time when this problem has been detected'
        past-attempts-to-fix:
          type: array
          x-key: date-of-attempt
          description: 'List of past attempts to fix the problem'
          items:
            type: object
            required:
              - date-of-attempt
              - response-code
            properties:
              date-of-attempt:
                type: string
                pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})$'
                description: 'Date and time when it was attempted to fix the problem'
              response-code:
                type: integer
                description: 'Code that resulted from the attempt to fix the problem'
        date-of-next-attempt-to-fix:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})$'
          description: 'Next attempt to fix this problem shall not be made before this date'
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: operation-key
    basicAuth:
      type: http
      scheme: basic
