openapi: 3.0.0
info:
  title: OpenDaylight
  version: 1.0.0
  description: MeasurementFunctions and ImplementationFunctions at the ApplicationDomainManager

paths:
########################################################################################################################
#   Measurements
########################################################################################################################
  /v1/provide-status-of-management-domain-interface:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
    post:
      operationId: provideStatusOfManagementDomainInterface
      summary: 'Provides information about a specified ManagementDomainInterface from OperationalDS'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - application-name
                - management-domain
              properties:
                application-name:
                  type: string
                  description: >
                    'Name of the application that holds the ManagementDomainInterface
                    from [CDM://p1/measure-management-domain-interface$request.body#application-name]'
                management-domain:
                  type: string
                  description: >
                    'Name of the ManagementDomain
                    from [CDM://p1/measure-management-domain-interface$request.body#management-domain]'
              example:
                application-name: 'MicroWaveDeviceInventory'
                management-domain: 'live'
      responses:
        '200':
          description: 'Information about ManagementDomainInterface provided from OperationalDS'
          content:
            application/json:
              schema:
                type: object
                required:
                  - remote-ip-address
                  - remote-port
                properties:
                  remote-ip-address:
                    type: string
                    description: 'Remote IP address at the TcpClient of the LTP identified by the managementDomain from OperationalDS'
                  remote-port:  
                    type: integer
                    description: 'Remote TCP port at the TcpClient of the LTP identified by the managementDomain from OperationalDS'
                example:
                  remote-ip-address: '127.0.0.1'
                  remote-port: 4711
          headers:
              x-correlator:
                schema:
                  type: string
                  example: '550e8400-e29b-11d4-a716-446655440000'
                description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
              exec-time:
                schema:
                  type: integer
                  example: 1100
                description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
              backend-time:
                schema:
                  type: integer
                  example: 850
                description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
              life-cycle-state:
                schema:
                  type: string
                  enum:
                    - 'EXPERIMENTAL'
                    - 'OPERATIONAL'
                    - 'DEPRECATED'
                    - 'OBSOLETE'
                    - 'UNKNOWN'
                    - 'NOT_YET_DEFINED'
                  example: 'EXPERIMENTAL'
                description: >
                  'Life cycle state of the consumed service
                  from [/core-model-1-4:control-construct/logical-termination-point=mm-1-0-0-op-s-is-002/layer-protocol=0/operation-server-interface-1-0:operation-server-interface-pac/operation-server-interface-configuration/life-cycle-state]'
        '400':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '401':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '403':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '404':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'


########################################################################################################################
#   Implementations
########################################################################################################################
  /v1/mediate-management-domain-interface-update:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
    post:
      operationId: mediateManagementDomainInterfaceUpdate
      summary: 'Passes through an update of a specified ManagementDomainInterface'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - application-name
                - management-domain
                - remote-ip-address
                - remote-port
              properties:
                application-name:
                  type: string
                  description: >
                    'Name of the application that holds the ManagementDomainInterface
                    from [CDM://p1/reconstruct-management-domain-interface$request.body#application-name]'
                management-domain:
                  type: string
                  description: >
                    'Name of the ManagementDomain towards the interface is
                    from [CDM://p1/reconstruct-management-domain-interface$request.body#management-domain]'
                remote-ip-address:
                  type: string
                  description: >
                    'New value of the remote IP address at the TcpClient of the LTP identified by the managementDomain
                    from [CDM://p1/reconstruct-management-domain-interface$request.body#remote-ip-address]'
                remote-port:  
                  type: integer
                  description: >
                    'New value of the remote TCP port at the TcpClient of the LTP identified by the managementDomain
                    from [CDM://p1/reconstruct-management-domain-interface$request.body#remote-port]'
              example:
                application-name: 'MicroWaveDeviceInventory'
                management-domain: 'live'
                remote-ip-address: '127.0.0.1'
                remote-port: 4712
      responses:
        '204':
          description: 'ManagementDomainInterface updated'
          headers:
            x-correlator:
              schema:
                type: string
                example: '550e8400-e29b-11d4-a716-446655440000'
              description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
            exec-time:
              schema:
                type: integer
                example: 1100
              description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
            backend-time:
              schema:
                type: integer
                example: 850
              description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
            life-cycle-state:
              schema:
                type: string
                enum:
                  - 'EXPERIMENTAL'
                  - 'OPERATIONAL'
                  - 'DEPRECATED'
                  - 'OBSOLETE'
                  - 'UNKNOWN'
                  - 'NOT_YET_DEFINED'
                example: 'EXPERIMENTAL'
              description: 'Life cycle state of the consumed service'
        '400':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '401':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '403':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '404':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'


########################################################################################################################
#   Common Components
########################################################################################################################
components:
  parameters:
    user:
      name: user
      in: header
      required: true
      schema:
        type: string
        example: 'User Name'
      description: 'User identifier from the system starting the service call'
    originator:
      name: originator
      in: header
      required: true
      schema:
        type: string
        minLength: 3
        example: 'Resolver'
      description: >
        'Identification for the system consuming the API, as defined in
         [/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]'
    x-correlator:
      name: x-correlator
      in: header
      required: true
      schema:
        type: string
        pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses'
    trace-indicator:
      name: trace-indicator
      in: header
      required: true
      schema:
        type: string
        pattern: '^([0-9]+)(\.([0-9]+))*$'
        example: '1.3.1'
      description: 'Sequence of request numbers along the flow'
    customer-journey:
      name: customer-journey
      in: header
      required: true
      schema:
        type: string
        example: 'Unknown value'
      description: 'Holds information supporting customer’s journey to which the execution applies'
  responses:
    responseForErroredServiceRequests:
      description: 'Response in case of errored service requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
      headers:
        x-correlator:
          schema:
            type: string
            pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
            example: '550e8400-e29b-11d4-a716-446655440000'
          description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
        exec-time:
          schema:
            type: integer
            example: 1100
          description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
    responseForErroredOamRequests:
      description: 'Response in case of errored OaM requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
  schemas:
    errorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: operation-key
